apiVersion: batch/v1
kind: Job
metadata: 
  name: yolov8-trainer-2gpus-fisheye
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nautilus.io/mizzou
                operator: In
                values:
                - NVIDIA-A100-SXM4-80GB-MIG-1g.10gb
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: code
        persistentVolumeClaim:
          claimName: code-vol

      containers:
      - name: gpu-container
        image: gitlab-registry.nrp-nautilus.io/yg5d6/yolov8
        command: ["/bin/sh", "-c"]
        args:
        - cd /workspace/FishEye8k/;
          mkdir dataset;
          tar -xvf Fisheye8K_all_including_train.tar.gz -C dataset/;
          wandb login a9d4d981ca28ba6b6729e2a29464674ca243b891;
          cp -r /workspace/code/fisheye_challenge .;
          cd fisheye_challenge;
          python -m torch.distributed.run --nproc_per_node 2 yolov8x_train_fisheye.py -devices 2 -epoch 10 -bs 16;
        resources:
          limits:
            memory: "32G"
            cpu: "8"
            nvidia.com/gpu: "2"
          requests:
            memory: "32G"
            cpu: "8"
            nvidia.com/gpu: "2"
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
        - name: code
          mountPath: /workspace/code
      restartPolicy: Never